(part "L7912CV"
    (packageRef "TO255P460X1020X2008-3P")
    (interface
        (port "1" (symbPinId 1) (portName "GND") (portType INOUT))
        (port "2" (symbPinId 2) (portName "IN") (portType INOUT))
        (port "3" (symbPinId 3) (portName "OUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "511-L7912CV")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/L7912CV?qs=hprEbj%252BdINrTD2aXjPyteQ%3D%3D")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "L7912CV")
    (property "Description" "L7912CV, Linear Voltage Regulator, Negative 1.5A -12 V, 3-Pin TO-220")
    (property "Datasheet_Link" "https://www.st.com/resource/en/datasheet/l79.pdf")
    (property "symbolName1" "L7912CV")
)
