(part "L7812CV"
    (packageRef "TO255P460X1020X2008-3P")
    (interface
        (port "1" (symbPinId 1) (portName "INPUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GROUND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "OUTPUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "511-L7812CV")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/L7812CV?qs=5Uvc6lfWVJzVGZQZmBynyg%3D%3D")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "L7812CV")
    (property "Description" "TO220 voltage regulator,L7812CV 12V 1.5A STMicroelectronics L7812CV, Single Linear Voltage Regulator, 1.5A 12 V, 3-Pin TO-220")
    (property "Datasheet_Link" "https://www.st.com/resource/en/datasheet/l78.pdf")
    (property "symbolName1" "L7812CV")
)
